vim.keymap.set('n', '<leader>fs', vim.cmd.Ag)
vim.keymap.set('n', '<leader>ff', vim.cmd.Files)
vim.keymap.set('n', '<leader>fb', vim.cmd.Buffers)
vim.keymap.set('n', '<leader>fc', vim.cmd.Commits)
vim.keymap.set('n', '<leader>fm', vim.cmd.Commands)
vim.keymap.set('n', '<leader>fl', vim.cmd.Lines)
